### ISSUE TITLE
"Cannot read from unknown characteristic" when connect to rolling spider via the BLE support from latest gobot

### ISSUE THREAD

**Issue by deadjoe** [hybridgroup/gobot#304]
Hi , after long waiting finally got the ble support to my device(rolling spider). #234 
Great works ! 
Just gave it a try and failed, below are the environment and running information.
Appreciate if any clue.
## 1. Environment

uname -a
Darwin bearbone-2.local 15.6.0 Darwin Kernel Version 15.6.0:

go version
go version go1.7 darwin/amd64
## 2.Return info by running gatt/example/discover.go

`go run discoverer.go`

```
Peripheral ID:8b2f8032290143e18fc7c426619632e8, NAME:()
  Local Name        = RS_B016314
  TX Power Level    = 0
  Manufacturer Data = [67 0 207 25 0 9 1 0]
  Service Data      = []

Peripheral ID:8b2f8032290143e18fc7c426619632e8, NAME:()
  Local Name        = RS_B016314
  TX Power Level    = 0
  Manufacturer Data = []
  Service Data      = []
```
## 3. Main test code

``` Go
package main

import (
        "fmt"
        "os"

        "github.com/hybridgroup/gobot"
        "github.com/hybridgroup/gobot/platforms/ble"
)

func main() {
        gbot := gobot.NewGobot()

        bleAdaptor := ble.NewBLEClientAdaptor("ble", os.Args[1])
        info := ble.NewBLEDeviceInformationDriver(bleAdaptor, "info")

        work := func() {
                fmt.Println("Model number:", info.GetModelNumber())
                fmt.Println("Firmware rev:", info.GetFirmwareRevision())
                fmt.Println("Hardware rev:", info.GetHardwareRevision())
                fmt.Println("Manufacturer name:", info.GetManufacturerName())
                fmt.Println("PnPId:", info.GetPnPId())
        }

        robot := gobot.NewRobot("bleBot",
                []gobot.Connection{bleAdaptor},
                []gobot.Device{info},
                work,
        )

        gbot.AddRobot(robot)

        gbot.Start()
}
```
## 4.Failed info when running the above test code

`go run spider.go 8b2f8032290143e18fc7c426619632e8 (this ID was obtained from the above discover.go step which represented to my rolling spider device)`

```
2016/08/28 01:21:55 Initializing Robot bleBot ...
2016/08/28 01:21:55 Initializing connections...
2016/08/28 01:21:55 Initializing connection ble ...
2016/08/28 01:21:55 Initializing devices...
2016/08/28 01:21:55 Initializing device info ...
2016/08/28 01:21:55 Starting Robot bleBot ...
2016/08/28 01:21:55 Starting connections...
2016/08/28 01:21:55 Starting connection ble...
State: PoweredOn
scanning...
2016/08/28 01:21:56 Unhandled event: xpc.Dict{"kCBMsgId":81, "kCBMsgArgs":xpc.Dict{"kCBMsgArgConnectionInterval":22, "kCBMsgArgConnectionLatency":0, "kCBMsgArgSupervisionTimeout":500, "kCBMsgArgDeviceUUID":xpc.UUID{0x8b, 0x2f, 0x80, 0x32, 0x29, 0x1, 0x43, 0xe1, 0x8f, 0xc7, 0xc4, 0x26, 0x61, 0x96, 0x32, 0xe8}}}
2016/08/28 01:21:56 Unhandled event: xpc.Dict{"kCBMsgArgs":xpc.Dict{"kCBMsgArgDeviceUUID":xpc.UUID{0x8b, 0x2f, 0x80, 0x32, 0x29, 0x1, 0x43, 0xe1, 0x8f, 0xc7, 0xc4, 0x26, 0x61, 0x96, 0x32, 0xe8}, "kCBMsgArgATTMTU":104}, "kCBMsgId":53}

Connected Peripheral ID:8b2f8032290143e18fc7c426619632e8, NAME:()
Failed to set MTU, err: Not implemented
2016/08/28 01:21:57 **Unhandled event: xpc.Dict{"kCBMsgId":81, "kCBMsgArgs":xpc.Dict{"kCBMsgArgConnectionInterval":18, "kCBMsgArgConnectionLatency":0, "kCBMsgArgSupervisionTimeout":500, "kCBMsgArgDeviceUUID":xpc.UUID{0x8b, 0x2f, 0x80, 0x32, 0x29, 0x1, 0x43, 0xe1, 0x8f, 0xc7, 0xc4, 0x26, 0x61, 0x96, 0x32, 0xe8}}}**
2016/08/28 01:22:00 Starting devices...
2016/08/28 01:22:00 Starting device info...
2016/08/28 01:22:00 Starting work...
2016/08/28 01:22:00 Unknown service ID: 180a
2016/08/28 01:22:00 Cannot read from unknown characteristic
Model number:
2016/08/28 01:22:00 Unknown service ID: 180a
2016/08/28 01:22:00 Cannot read from unknown characteristic
Firmware rev:
2016/08/28 01:22:00 Unknown service ID: 180a
2016/08/28 01:22:00 Cannot read from unknown characteristic
Hardware rev:
2016/08/28 01:22:00 Unknown service ID: 180a
2016/08/28 01:22:00 Cannot read from unknown characteristic
Manufacturer name:
2016/08/28 01:22:00 Unknown service ID: 180a
2016/08/28 01:22:00 Cannot read from unknown characteristic
PnPId:
```

**Comment by deadjoe** [comment]
Just to confirm that the central to device are working well, i tried the cylon.js via https://github.com/ChrisTheBaron/cylon-rolling-spider and it does working perfect.

```
"use strict";

var Cylon = require("cylon");

Cylon.robot({
       	connections: {
       		/*
       		 * Remember to change the uuid to your own devices uuid
       		 */
       		spider: { adaptor: "rolling-spider", uuid: "8b2f8032290143e18fc7c426619632e8" }
       	},

       	devices: {
       		drone: { driver: "rolling-spider" }
       	},

       	work: function (my) {
       		my.drone.wheelOn();
       		my.drone.flatTrim();
       		my.drone.takeOff();

       		after(5000, function () {
       			my.drone.land();
       		});
       	}
}).start();
```

**Comment by deadprogram** [comment]
Wow @deadjoe that is one incredibly well entered Github issue. Let me look into that on my OSX machine, and I will get back to you.

**Comment by deadjoe** [comment]
Any luck  or clue?

**Comment by deadprogram** [comment]
Hi @deadjoe I do not think that the Parrot Minidrone supports those particular characteristics. Did you try running https://github.com/hybridgroup/gobot/blob/master/examples/minidrone.go by any chance?

**Comment by deadjoe** [comment]
Hi @deadprogram , below are the result when running minidrone.go

```
 examples git:(master) ✗ go run minidrone.go 8b2f8032290143e18fc7c426619632e8
2016/09/22 21:33:38 Initializing Robot bleBot ...
2016/09/22 21:33:38 Initializing connections...
2016/09/22 21:33:38 Initializing connection ble ...
2016/09/22 21:33:38 Initializing devices...
2016/09/22 21:33:38 Initializing device drone ...
2016/09/22 21:33:38 Starting Robot bleBot ...
2016/09/22 21:33:38 Starting connections...
2016/09/22 21:33:38 Starting connection ble...
State: PoweredOn
scanning...
2016/09/22 21:33:39 Unhandled event: xpc.Dict{"kCBMsgId":81, "kCBMsgArgs":xpc.Dict{"kCBMsgArgConnectionInterval":22, "kCBMsgArgConnectionLatency":0, "kCBMsgArgSupervisionTimeout":500, "kCBMsgArgDeviceUUID":xpc.UUID{0x8b, 0x2f, 0x80, 0x32, 0x29, 0x1, 0x43, 0xe1, 0x8f, 0xc7, 0xc4, 0x26, 0x61, 0x96, 0x32, 0xe8}}}
2016/09/22 21:33:39 Unhandled event: xpc.Dict{"kCBMsgId":53, "kCBMsgArgs":xpc.Dict{"kCBMsgArgDeviceUUID":xpc.UUID{0x8b, 0x2f, 0x80, 0x32, 0x29, 0x1, 0x43, 0xe1, 0x8f, 0xc7, 0xc4, 0x26, 0x61, 0x96, 0x32, 0xe8}, "kCBMsgArgATTMTU":104}}

Connected Peripheral ID:8b2f8032290143e18fc7c426619632e8, NAME:()
Failed to set MTU, err: Not implemented
2016/09/22 21:33:40 Unhandled event: xpc.Dict{"kCBMsgId":81, "kCBMsgArgs":xpc.Dict{"kCBMsgArgConnectionInterval":18, "kCBMsgArgConnectionLatency":0, "kCBMsgArgSupervisionTimeout":500, "kCBMsgArgDeviceUUID":xpc.UUID{0x8b, 0x2f, 0x80, 0x32, 0x29, 0x1, 0x43, 0xe1, 0x8f, 0xc7, 0xc4, 0x26, 0x61, 0x96, 0x32, 0xe8}}}
2016/09/22 21:33:41 Starting devices...
2016/09/22 21:33:41 Starting device drone...
2016/09/22 21:33:41 Starting work...
[4 1 2 3 0 0]
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 35 [running]:
panic(0x40ea540, 0xc42011c450)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/currantlabs/gatt/xpc._cgoCheckPointer0(0xc42005a104, 0x0, 0x0, 0x0, 0x40dd601)
	??:0 +0x59
github.com/currantlabs/gatt/xpc.valueToXpc(0x40dd6e0, 0xc42011a5e0, 0x97, 0x40dd6e0)
	/Users/joe/goproj/src/github.com/currantlabs/gatt/xpc/xpc_darwin.go:254 +0x3ff
github.com/currantlabs/gatt/xpc.valueToXpc(0x40e7f80, 0xc42011c440, 0x94, 0x40df300)
	/Users/joe/goproj/src/github.com/currantlabs/gatt/xpc/xpc_darwin.go:269 +0x68b
github.com/currantlabs/gatt/xpc.valueToXpc(0x40fe180, 0xc420113890, 0x15, 0x40fe180)
	/Users/joe/goproj/src/github.com/currantlabs/gatt/xpc/xpc_darwin.go:239 +0x8b2
github.com/currantlabs/gatt/xpc.valueToXpc(0x40e7f80, 0xc42011c380, 0x94, 0x40df300)
	/Users/joe/goproj/src/github.com/currantlabs/gatt/xpc/xpc_darwin.go:269 +0x68b
github.com/currantlabs/gatt/xpc.valueToXpc(0x40fe180, 0xc4201138c0, 0x15, 0xc4201138c0)
	/Users/joe/goproj/src/github.com/currantlabs/gatt/xpc/xpc_darwin.go:239 +0x8b2
github.com/currantlabs/gatt/xpc.goToXpc(0x40fe180, 0xc4201138c0, 0x0)
	/Users/joe/goproj/src/github.com/currantlabs/gatt/xpc/xpc_darwin.go:213 +0x57
github.com/currantlabs/gatt/xpc.(*XPC).Send(0xc4200a0030, 0x40fe180, 0xc4201138c0, 0xc4200d6e00)
	/Users/joe/goproj/src/github.com/currantlabs/gatt/xpc/xpc_darwin.go:23 +0x85
github.com/currantlabs/gatt.(*device).sendCBMsg(0xc4200a0000, 0x42, 0xc420113890)
	/Users/joe/goproj/src/github.com/currantlabs/gatt/device_darwin.go:509 +0x15b
github.com/currantlabs/gatt.(*peripheral).loop.func1(0xc4200a0200, 0xc4200cc3c0)
	/Users/joe/goproj/src/github.com/currantlabs/gatt/peripheral_darwin.go:243 +0x119
created by github.com/currantlabs/gatt.(*peripheral).loop
	/Users/joe/goproj/src/github.com/currantlabs/gatt/peripheral_darwin.go:253 +0x7f
exit status 2
```

**Comment by deadjoe** [comment]
and corresponding code of /Users/joe/goproj/src/github.com/currantlabs/gatt/peripheral_darwin.go:253 is 

```
236 func (p *peripheral) loop() {
237         rspc := make(chan message)
238
239         go func() {
240                 for {
241                         select {
242                         case req := <-p.reqc:
243                                 p.d.sendCBMsg(req.id, req.args)
244                                 if req.rspc == nil {
245                                         break
246                                 }
247                                 m := <-rspc
248                                 req.rspc <- m.args
249                         case <-p.quitc:
250                                 return
251                         }
252                 }
253         }()
```

**Comment by deadprogram** [comment]
Hi, @deadjoe 

Just noticed you have the `panic: runtime error: cgo argument has Go pointer to Go pointer` error as discussed here: https://github.com/hybridgroup/gobot/issues/298

Please try running your code like this:

```
GODEBUG=cgocheck=0 go run minidrone.go 8b2f8032290143e18fc7c426619632e8
```

**Comment by deadprogram** [comment]
Hi @deadjoe did you ever have a chance to try the command i suggested?

**Comment by juliancheal** [comment]
I have a feeling this is related to https://github.com/currantlabs/ble/issues/16 in either `currantlabs/ble` or `currantlabs/gatt`

**Comment by deadprogram** [comment]
The docs are now updated with this info. Thanks, everyone.
