### ISSUE TITLE
tello_opencv.go fails to work properly

### ISSUE THREAD

**Issue by zeushammer** [hybridgroup/gobot#604]
Using the latest versions of all dependencies on mac osx I receive the following output:

```
2018/08/31 23:46:08 Initializing connections...
2018/08/31 23:46:08 Initializing devices...
2018/08/31 23:46:08 Initializing device Tello-63BBAD0715B7E0AA ...
2018/08/31 23:46:08 Initializing device Window ...
2018/08/31 23:46:08 Robot tello initialized.
2018/08/31 23:46:08 Starting Robot tello ...
2018/08/31 23:46:08 Starting connections...
2018/08/31 23:46:08 Starting devices...
2018/08/31 23:46:08 Starting device Tello-63BBAD0715B7E0AA...
2018/08/31 23:46:08 Starting device Window...
2018/08/31 23:46:08 Starting work...
Connected
2018-08-31 23:46:13.449 killerdrone[1547:10991] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'nextEventMatchingMask should only be called from the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff285382db __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff4f6d9c76 objc_exception_throw + 48
	2   AppKit                              0x00007fff261e4297 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 4167
	3   libopencv_highgui.3.4.dylib         0x0000000005cec60e cvWaitKey + 366
	4   libopencv_highgui.3.4.dylib         0x0000000005ce71a2 _ZN2cv7waitKeyEi + 50
	5   killerdrone                         0x0000000004110a7c _cgo_15112270eda1_Cfunc_Window_WaitKey + 28
	6   killerdrone                         0x0000000004057c80 runtime.asmcgocall + 112
)
libc++abi.dylib: terminating with uncaught exception of type NSException
SIGABRT: abort
PC=0x7fff50443b66 m=14 sigcode=0

goroutine 0 [idle]:
runtime: unknown pc 0x7fff50443b66
stack: frame={sp:0x700000c05498, fp:0x0} stack=[0x700000b87290,0x700000c06e90)
0000700000c05398:  00000068288a6b68  00007000ffff4208
0000700000c053a8:  0000000008925930  000000000000007f
0000700000c053b8:  0000007b284333d8  00000000ffff4208
0000700000c053c8:  0000700000c05400  000070000000007f
0000700000c053d8:  0000000000000001  0000000000000000
0000700000c053e8:  0000000032aaaba2  0000000000000000
0000700000c053f8:  0000700000c05530  0000000000000000
0000700000c05408:  0000000032aaaba2  0000000000000000
0000700000c05418:  0000000000000000  0000000000000000
0000700000c05428:  0000000000000000  0000000000000000
0000700000c05438:  0000000000000000  0000000000000000
0000700000c05448:  0000000000000003  0000000000000000
0000700000c05458:  0000000000000000  0000000000000000
0000700000c05468:  0000000000000000  00007fff88de6240
0000700000c05478:  00007fff88de5ca0  00007fff5037e366
0000700000c05488:  0000000000000000  0000700000c054d0
0000700000c05498: <00007fff5060e080  0000700000c07000
0000700000c054a8:  0000700000c054e8  0000000000000008
0000700000c054b8:  0000000000000030  00007fff4e2ba501
0000700000c054c8:  00007fff88de69a0  0000700000c05500
0000700000c054d8:  00007fff5039f1ae  0000000000000008
0000700000c054e8:  00000000ffffffdf  ffffffff4e2ba501
0000700000c054f8:  0000700000c05600  0000700000c05630
0000700000c05508:  00007fff4e299f8f  0000003000000018
0000700000c05518:  0000700000c05640  0000700000c05550
0000700000c05528:  0000700000c05740  0000003000000018
0000700000c05538:  0000700000c05640  0000700000c05550
0000700000c05548:  0000700000c05748  00000000000007e2
0000700000c05558:  00007fff4e2ba55c  00007fff288b96dd
0000700000c05568:  00007fff4f6e855f  0000000000000000
0000700000c05578:  02aaaaaaaaaaaaaa  0000700000c05380
0000700000c05588:  0000000000000000  0000700000c05620
runtime: unknown pc 0x7fff50443b66
stack: frame={sp:0x700000c05498, fp:0x0} stack=[0x700000b87290,0x700000c06e90)
0000700000c05398:  00000068288a6b68  00007000ffff4208
0000700000c053a8:  0000000008925930  000000000000007f
0000700000c053b8:  0000007b284333d8  00000000ffff4208
0000700000c053c8:  0000700000c05400  000070000000007f
0000700000c053d8:  0000000000000001  0000000000000000
0000700000c053e8:  0000000032aaaba2  0000000000000000
0000700000c053f8:  0000700000c05530  0000000000000000
0000700000c05408:  0000000032aaaba2  0000000000000000
0000700000c05418:  0000000000000000  0000000000000000
0000700000c05428:  0000000000000000  0000000000000000
0000700000c05438:  0000000000000000  0000000000000000
0000700000c05448:  0000000000000003  0000000000000000
0000700000c05458:  0000000000000000  0000000000000000
0000700000c05468:  0000000000000000  00007fff88de6240
0000700000c05478:  00007fff88de5ca0  00007fff5037e366
0000700000c05488:  0000000000000000  0000700000c054d0
0000700000c05498: <00007fff5060e080  0000700000c07000
0000700000c054a8:  0000700000c054e8  0000000000000008
0000700000c054b8:  0000000000000030  00007fff4e2ba501
0000700000c054c8:  00007fff88de69a0  0000700000c05500
0000700000c054d8:  00007fff5039f1ae  0000000000000008
0000700000c054e8:  00000000ffffffdf  ffffffff4e2ba501
0000700000c054f8:  0000700000c05600  0000700000c05630
0000700000c05508:  00007fff4e299f8f  0000003000000018
0000700000c05518:  0000700000c05640  0000700000c05550
0000700000c05528:  0000700000c05740  0000003000000018
0000700000c05538:  0000700000c05640  0000700000c05550
0000700000c05548:  0000700000c05748  00000000000007e2
0000700000c05558:  00007fff4e2ba55c  00007fff288b96dd
0000700000c05568:  00007fff4f6e855f  0000000000000000
0000700000c05578:  02aaaaaaaaaaaaaa  0000700000c05380
0000700000c05588:  0000000000000000  0000700000c05620

goroutine 12 [syscall]:
runtime.cgocall(0x4110a60, 0xc0000e8f00, 0x0)
	/Users/zeushammer/go/src/runtime/cgocall.go:128 +0x5e fp=0xc0000e8ec8 sp=0xc0000e8e90 pc=0x4004fee
gocv.io/x/gocv._Cfunc_Window_WaitKey(0x1, 0x0)
	_cgo_gotypes.go:4713 +0x4d fp=0xc0000e8f00 sp=0xc0000e8ec8 pc=0x410c5bd
gocv.io/x/gocv.WaitKey(0x1, 0x8a20290)
	/Users/zeushammer/gocode/src/gocv.io/x/gocv/highgui.go:240 +0x2a fp=0xc0000e8f20 sp=0xc0000e8f00 pc=0x410cbaa
gobot.io/x/gobot/platforms/opencv.(*WindowDriver).WaitKey(0xc000092630, 0x1, 0x10)
	/Users/zeushammer/gocode/src/gobot.io/x/gobot/platforms/opencv/window_driver.go:55 +0x2b fp=0xc0000e8f40 sp=0xc0000e8f20 pc=0x410d30b
main.main.func1.1(0x41934e0, 0xc00000e0b8, 0xc000092630)
	/Users/zeushammer/gocode/src/killerdrone/main.go:58 +0x1c3 fp=0xc0000e8fc8 sp=0xc0000e8f40 pc=0x410d883
runtime.goexit()
	/Users/zeushammer/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0000e8fd0 sp=0xc0000e8fc8 pc=0x40584e1
created by main.main.func1
	/Users/zeushammer/gocode/src/killerdrone/main.go:42 +0x17c

goroutine 1 [chan receive, locked to thread]:
gobot.io/x/gobot.(*Robot).Start(0xc0000b4000, 0x0, 0x0, 0x0, 0x400e288, 0x10)
	/Users/zeushammer/gocode/src/gobot.io/x/gobot/robot.go:180 +0x294
main.main()
	/Users/zeushammer/gocode/src/killerdrone/main.go:87 +0x230

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/Users/zeushammer/go/src/runtime/sigqueue.go:139 +0x9f
os/signal.loop()
	/Users/zeushammer/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/Users/zeushammer/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 6 [chan receive]:
gobot.io/x/gobot.NewEventer.func1(0xc00000c1e0)
	/Users/zeushammer/gocode/src/gobot.io/x/gobot/eventer.go:67 +0xab
created by gobot.io/x/gobot.NewEventer
	/Users/zeushammer/gocode/src/gobot.io/x/gobot/eventer.go:64 +0xba

goroutine 7 [chan receive]:
gobot.io/x/gobot.NewEventer.func1(0xc00000c2c0)
	/Users/zeushammer/gocode/src/gobot.io/x/gobot/eventer.go:67 +0xab
created by gobot.io/x/gobot.NewEventer
	/Users/zeushammer/gocode/src/gobot.io/x/gobot/eventer.go:64 +0xba

goroutine 8 [IO wait]:
internal/poll.runtime_pollWait(0x8c94f00, 0x72, 0xc000336ca0)
	/Users/zeushammer/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc0000c6098, 0x72, 0xffffffffffffff00, 0x4193240, 0x426ad30)
	/Users/zeushammer/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc0000c6098, 0xc00040c800, 0x800, 0x800)
	/Users/zeushammer/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc0000c6080, 0xc00040c800, 0x800, 0x800, 0x0, 0x0, 0x0)
	/Users/zeushammer/go/src/internal/poll/fd_unix.go:169 +0x1d6
net.(*netFD).Read(0xc0000c6080, 0xc00040c800, 0x800, 0x800, 0xc000336db0, 0x400e288, 0x800)
	/Users/zeushammer/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000e098, 0xc00040c800, 0x800, 0x800, 0x0, 0x0, 0x0)
	/Users/zeushammer/go/src/net/net.go:177 +0x68
gobot.io/x/gobot/platforms/dji/tello.(*Driver).handleResponse(0xc0000a80a0, 0x4192d20, 0xc00000e098, 0x0, 0x0)
	/Users/zeushammer/gocode/src/gobot.io/x/gobot/platforms/dji/tello/driver.go:750 +0x7b
gobot.io/x/gobot/platforms/dji/tello.(*Driver).Start.func1(0xc0000a80a0, 0xc00000e098)
	/Users/zeushammer/gocode/src/gobot.io/x/gobot/platforms/dji/tello/driver.go:262 +0xf1
created by gobot.io/x/gobot/platforms/dji/tello.(*Driver).Start
	/Users/zeushammer/gocode/src/gobot.io/x/gobot/platforms/dji/tello/driver.go:255 +0x2cd

goroutine 18 [chan receive]:
gobot.io/x/gobot.(*eventer).On.func1(0xc0000ce000, 0x41731ad, 0x9, 0xc0000ca000)
	/Users/zeushammer/gocode/src/gobot.io/x/gobot/eventer.go:129 +0x4b
created by gobot.io/x/gobot.(*eventer).On
	/Users/zeushammer/gocode/src/gobot.io/x/gobot/eventer.go:126 +0x6b

goroutine 9 [sleep]:
time.Sleep(0x1312d00)
	/Users/zeushammer/go/src/runtime/time.go:105 +0x14f
gobot.io/x/gobot/platforms/dji/tello.(*Driver).Start.func2(0xc0000a80a0)
	/Users/zeushammer/gocode/src/gobot.io/x/gobot/platforms/dji/tello/driver.go:279 +0x30
created by gobot.io/x/gobot/platforms/dji/tello.(*Driver).Start
	/Users/zeushammer/gocode/src/gobot.io/x/gobot/platforms/dji/tello/driver.go:273 +0x314

goroutine 11 [chan receive]:
gobot.io/x/gobot.(*Robot).Start.func2(0xc0000b4000)
	/Users/zeushammer/gocode/src/gobot.io/x/gobot/robot.go:171 +0x46
created by gobot.io/x/gobot.(*Robot).Start
	/Users/zeushammer/gocode/src/gobot.io/x/gobot/robot.go:169 +0x1e2

goroutine 13 [chan receive]:
gobot.io/x/gobot.(*eventer).On.func1(0xc000080540, 0x41731ad, 0x9, 0xc000010710)
	/Users/zeushammer/gocode/src/gobot.io/x/gobot/eventer.go:129 +0x4b
created by gobot.io/x/gobot.(*eventer).On
	/Users/zeushammer/gocode/src/gobot.io/x/gobot/eventer.go:126 +0x6b

goroutine 14 [chan receive]:
gobot.io/x/gobot.(*eventer).On.func1(0xc0000805a0, 0x41734dc, 0xa, 0xc00000c400)
	/Users/zeushammer/gocode/src/gobot.io/x/gobot/eventer.go:129 +0x4b
created by gobot.io/x/gobot.(*eventer).On
	/Users/zeushammer/gocode/src/gobot.io/x/gobot/eventer.go:126 +0x6b

goroutine 15 [chan receive]:
gobot.io/x/gobot.Every.func1(0xc0000a2230, 0xc000010720)
	/Users/zeushammer/gocode/src/gobot.io/x/gobot/utils.go:21 +0x31
created by gobot.io/x/gobot.Every
	/Users/zeushammer/gocode/src/gobot.io/x/gobot/utils.go:18 +0x5c

goroutine 20 [IO wait]:
internal/poll.runtime_pollWait(0x8c94bc0, 0x72, 0x0)
	/Users/zeushammer/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc00033e018, 0x72, 0x0, 0x0, 0x0)
	/Users/zeushammer/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc00033e018, 0xc000415000, 0x800, 0x800)
	/Users/zeushammer/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).ReadFrom(0xc00033e000, 0xc000415000, 0x800, 0x800, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/zeushammer/go/src/internal/poll/fd_unix.go:219 +0x168
net.(*netFD).readFrom(0xc00033e000, 0xc000415000, 0x800, 0x800, 0xc000332e98, 0x400750f, 0xc000080240, 0x400d9ff, 0xc000332ef0)
	/Users/zeushammer/go/src/net/fd_unix.go:208 +0x5b
net.(*UDPConn).readFrom(0xc0000da008, 0xc000415000, 0x800, 0x800, 0x414f401, 0x40ccf7c, 0xc000332ef8, 0x40417a7)
	/Users/zeushammer/go/src/net/udpsock_posix.go:47 +0x6a
net.(*UDPConn).ReadFromUDP(0xc0000da008, 0xc000415000, 0x800, 0x800, 0x800, 0x800, 0x0, 0x0)
	/Users/zeushammer/go/src/net/udpsock.go:109 +0x6d
gobot.io/x/gobot/platforms/dji/tello.(*Driver).processVideo.func1(0xc0000a80a0)
	/Users/zeushammer/gocode/src/gobot.io/x/gobot/platforms/dji/tello/driver.go:818 +0x8e
created by gobot.io/x/gobot/platforms/dji/tello.(*Driver).processVideo
	/Users/zeushammer/gocode/src/gobot.io/x/gobot/platforms/dji/tello/driver.go:815 +0xde

rax    0x0
rbx    0x700000c07000
rcx    0x700000c05498
rdx    0x0
rdi    0x9f03
rsi    0x6
rbp    0x700000c054d0
rsp    0x700000c05498
r8     0x700000c05360
r9     0x700000c05530
r10    0x0
r11    0x206
r12    0x9f03
r13    0x30
r14    0x6
r15    0x2d
rip    0x7fff50443b66
rflags 0x206
cs     0x7
fs     0x0
gs     0x0
```

**Comment by trevrosen** [comment]
Thanks for your interest in gobot and apologies for the late reply! Gocv is compatible with both OpenCV 3 and 4. I've attempted to repro your issue on macOS Mojave w/ OpenCV 3.4.5 and I get a fully functional output. With more information on your specific platform, we may be able to help, but I'm going to close this for now. Feel free to pop into `#gobot` in Gophers Slack if you'd like to discuss in real time.
