### ISSUE TITLE
spi.SpiConnection is not gobot.Connection: missing method Connect

### ISSUE THREAD

**Issue by davidvanlaatum** [hybridgroup/gobot#794]
```package main

import (
	"gobot.io/x/gobot"
	"gobot.io/x/gobot/api"
	"gobot.io/x/gobot/drivers/spi"
	"gobot.io/x/gobot/platforms/raspi"
)

func main() {
	mbot := gobot.NewMaster()

	a := api.NewAPI(mbot)
	a.Start()

	r := raspi.NewAdaptor()
	ai := spi.NewMCP3008Driver(r, func(config spi.Config) {
		config.WithBus(1)
	})

	robot := gobot.NewRobot(
		[]gobot.Connection{r},
		[]gobot.Device{ai},
	)

	mbot.AddRobot(robot)

	mbot.Start()
}
```

```2021/05/27 20:31:14 Initializing API on :3000...
2021/05/27 20:31:14 WARNING: API using insecure connection. We recommend using an SSL certificate with Gobot.
2021/05/27 20:31:14 Initializing connections...
2021/05/27 20:31:14 Initializing connection RaspberryPi-78E59E2465D100FE ...
2021/05/27 20:31:14 Initializing devices...
2021/05/27 20:31:14 Initializing device MCP3008-5E4954DB19DCBD4B ...
2021/05/27 20:31:14 Robot 6A2A7C251008C969 initialized.
2021/05/27 20:31:14 Starting Robot 6A2A7C251008C969 ...
2021/05/27 20:31:14 Starting connections...
2021/05/27 20:31:14 Starting connection RaspberryPi-78E59E2465D100FE...
2021/05/27 20:31:14 Starting devices...
2021/05/27 20:31:14 Starting device MCP3008-5E4954DB19DCBD4B...
2021/05/27 20:31:14 Starting work...
2021/05/27 20:31:34 http: panic serving 192.168.83.91:60963: interface conversion: *spi.SpiConnection is not gobot.Connection: missing method Connect
goroutine 49 [running]:
net/http.(*conn).serve.func1(0x400014c000)
	/usr/local/Cellar/go/1.16.2/libexec/src/net/http/server.go:1824 +0x110
panic(0x28a5a0, 0x40002d6600)
	/usr/local/Cellar/go/1.16.2/libexec/src/runtime/panic.go:971 +0x424
gobot.io/x/gobot/drivers/spi.(*MCP3008Driver).Connection(0x40000b8230, 0x40002a2140, 0x12)
	/Users/david/go/pkg/mod/gobot.io/x/gobot@v1.15.0/drivers/spi/mcp3008.go:53 +0x40
gobot.io/x/gobot.NewJSONDevice(0x33f798, 0x40000b8230, 0x400005d500)
	/Users/david/go/pkg/mod/gobot.io/x/gobot@v1.15.0/device.go:26 +0x10c
gobot.io/x/gobot.NewJSONRobot.func1(0x33f798, 0x40000b8230)
	/Users/david/go/pkg/mod/gobot.io/x/gobot@v1.15.0/robot.go:37 +0x40
gobot.io/x/gobot.(*Devices).Each(0x40000a6120, 0x400013b5f0)
	/Users/david/go/pkg/mod/gobot.io/x/gobot@v1.15.0/device.go:51 +0x70
gobot.io/x/gobot.NewJSONRobot(0x4000190000, 0x0)
	/Users/david/go/pkg/mod/gobot.io/x/gobot@v1.15.0/robot.go:36 +0x208
gobot.io/x/gobot.NewJSONMaster.func1(0x4000190000)
	/Users/david/go/pkg/mod/gobot.io/x/gobot@v1.15.0/master.go:29 +0x30
gobot.io/x/gobot.(*Robots).Each(0x40000a60a8, 0x400013b788)
	/Users/david/go/pkg/mod/gobot.io/x/gobot@v1.15.0/robot.go:100 +0x50
gobot.io/x/gobot.NewJSONMaster(0x40000b8190, 0x2279f0)
	/Users/david/go/pkg/mod/gobot.io/x/gobot@v1.15.0/master.go:28 +0x1cc
gobot.io/x/gobot/api.(*API).mcp(0x40000fc000, 0x33e5d0, 0x4000074460, 0x40002a4500)
	/Users/david/go/pkg/mod/gobot.io/x/gobot@v1.15.0/api/api.go:188 +0x38
net/http.HandlerFunc.ServeHTTP(0x4000097230, 0x33e5d0, 0x4000074460, 0x40002a4500)
	/usr/local/Cellar/go/1.16.2/libexec/src/net/http/server.go:2069 +0x40
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0x40000a60c0, 0x33e5d0, 0x4000074460, 0x40002a4500)
	/Users/david/go/pkg/mod/github.com/bmizerany/pat@v0.0.0-20170815010413-6226ea591a40/mux.go:117 +0x104
gobot.io/x/gobot/api.(*API).ServeHTTP(0x40000fc000, 0x33e5d0, 0x4000074460, 0x40002a4500)
	/Users/david/go/pkg/mod/gobot.io/x/gobot@v1.15.0/api/api.go:65 +0x2b8
net/http.(*ServeMux).ServeHTTP(0x55d0e0, 0x33e5d0, 0x4000074460, 0x40002a4500)
	/usr/local/Cellar/go/1.16.2/libexec/src/net/http/server.go:2448 +0x190
net/http.serverHandler.ServeHTTP(0x400010c000, 0x33e5d0, 0x4000074460, 0x40002a4500)
	/usr/local/Cellar/go/1.16.2/libexec/src/net/http/server.go:2887 +0xbc
net/http.(*conn).serve(0x400014c000, 0x33ec20, 0x4000072280)
	/usr/local/Cellar/go/1.16.2/libexec/src/net/http/server.go:1952 +0x71c
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.16.2/libexec/src/net/http/server.go:3013 +0x318
```

Just going to :3000/  shows this, am I doing something wrong?

**Comment by stevebargelt** [comment]
I'm seeing the same error when trying to GET any API endpoint with a RaspberryPi and and SPI connection.

**Comment by gen2thomas** [comment]
part of release v2.0.0
